all:
  children:
    esxi:
      hosts: 192.168.0.2
      vars:
        ansible_user: root
    dev:
      hosts: localhost
      vars:
        ansible_connection: local
        ansible_python_interpreter: python3
    web_server:
      children:
        growi:
          hosts: ubuntu01
        keywoo:
          hosts: centos01
