- name: copy config file
  copy:
    src: 'fish/config.fish'
    dest: '{{ ansible_user_dir }}/.config/fish/'
    mode: '0644'

- name: register fish path
  command: 'which fish'
  register: fish_path
  changed_when: False
  check_mode: no

- name: apply fish to user shell
  user:
    name: '{{ ansible_user }}'
    shell: '{{ fish_path.stdout }}'
  when: ansible_user_shell != fish_path.stdout
  become: yes

- name: install oh-my-fish
  shell: 'curl -L https://get.oh-my.fish | fish'
  args:
    creates: '~/.config/fish/conf.d/omf.fish'
